// AUTO-GENERATED by tests/bin/json-to-playwright.php — edit the converter or JSON source, then regenerate.

import { test } from '@playwright/test';

import { assertOrderNowSubmitting, clickOrderNowRepeated } from '../support/checkout-flow-steps';

import { RegressionConfig } from '../support/regression-config';
import { fillCard } from '../support/stripe-steps';

import { SmokeConfig } from '../support/smoke-config';
import { skipUnlessSmokeUrl } from '../support/smoke-skip';

const config = SmokeConfig.fromEnv();
const stripeConfig = RegressionConfig.fromEnv();

test('ST-004 duplicate submit is prevented', { tag: ["@smoke","@stripe"] }, async ({ page }) => {
  test.setTimeout(300000);
  skipUnlessSmokeUrl(config, 'checkout_stripe_url');

  await page.goto(config.pagePath('checkout_stripe_url'));
  await fillCard(page, stripeConfig);
  await page.locator('#first_name').fill(config.var('first_name'));
  await page.locator('#last_name').fill(config.var('last_name'));
  await page.locator('#email').fill(config.uniqueEmail('st004'));
  await page.locator('#phone').fill(config.var('phone'));
  await clickOrderNowRepeated(page, 2);
  await assertOrderNowSubmitting(page);
});
