// AUTO-GENERATED by tests/bin/json-to-playwright.php — edit the converter or JSON source, then regenerate.

import { test } from '@playwright/test';

import { assertOrderReceived, clickOrderNow } from '../support/checkout-flow-steps';

import { RegressionConfig } from '../support/regression-config';
import { fillCard } from '../support/stripe-steps';

import { SmokeConfig } from '../support/smoke-config';
import { skipUnlessSmokeUrl } from '../support/smoke-skip';

const config = SmokeConfig.fromEnv();
const stripeConfig = RegressionConfig.fromEnv();

test('ST-001 Stripe one-time checkout succeeds', { tag: ["@smoke","@stripe"] }, async ({ page }) => {
  test.setTimeout(300000);
  skipUnlessSmokeUrl(config, 'checkout_stripe_url');

  await page.goto(config.pagePath('checkout_stripe_url'));
  await fillCard(page, stripeConfig);
  await page.locator('#first_name').fill('GI');
  await page.locator('#last_name').fill('PublishPress Cart');
  await page.locator('#email').fill(config.uniqueEmail('st001'));
  await page.locator('#phone').fill('5550101001');
  await clickOrderNow(page);
  await assertOrderReceived(page);
});
