// AUTO-GENERATED by tests/bin/json-to-playwright.php — edit the converter or JSON source, then regenerate.

import { test } from '@playwright/test';

import { assertBodyContains, clickOrderNowForValidation } from '../support/checkout-flow-steps';

import { SmokeConfig } from '../support/smoke-config';
import { skipUnlessSmokeUrl } from '../support/smoke-skip';

const config = SmokeConfig.fromEnv();

test('ST-003 required checkout fields validate', { tag: ["@smoke","@stripe"] }, async ({ page }) => {
  test.setTimeout(300000);
  skipUnlessSmokeUrl(config, 'checkout_stripe_url');

  await page.goto(config.pagePath('checkout_stripe_url'));
  await page.locator('#email').waitFor({ state: 'visible', timeout: 30_000 });
  await clickOrderNowForValidation(page);
  await assertBodyContains(page, 'required');
  await page.locator('#email').fill('not-an-email');
  await clickOrderNowForValidation(page);
  await assertBodyContains(page, 'email');
});
