// AUTO-GENERATED by tests/bin/json-to-playwright.php — edit the converter or JSON source, then regenerate.

import { expect, test } from '@playwright/test';

import { assertBodyContains, clickOrderNowForValidation, clickTermsCheckbox } from '../support/checkout-flow-steps';

import { SmokeConfig } from '../support/smoke-config';
import { skipUnlessSmokeUrl } from '../support/smoke-skip';

const config = SmokeConfig.fromEnv();

test('ST-009 terms checkbox is required', { tag: ["@smoke"] }, async ({ page }) => {
  test.setTimeout(300000);
  skipUnlessSmokeUrl(config, 'checkout_terms_url');

  await page.goto(config.pagePath('checkout_terms_url'));
  await page.locator('#ppcart_accept_terms').waitFor({ state: 'visible', timeout: 30_000 });
  await clickOrderNowForValidation(page);
  await assertBodyContains(page, 'terms');
  await clickTermsCheckbox(page);
  await expect(page.locator('#ppcart_accept_terms')).toBeChecked();
});
