// AUTO-GENERATED by tests/bin/json-to-playwright.php — edit the converter or JSON source, then regenerate.

import { test } from '@playwright/test';

import { assertBodyContains, assertElementNotPresent } from '../support/checkout-flow-steps';

import { SmokeConfig } from '../support/smoke-config';
import { skipUnlessSmokeUrl } from '../support/smoke-skip';

const config = SmokeConfig.fromEnv();

test('ST-014 single payment plan displays correctly', { tag: ["@smoke","@stripe"] }, async ({ page }) => {
  test.setTimeout(300000);
  skipUnlessSmokeUrl(config, 'checkout_stripe_url');

  await page.goto(config.pagePath('checkout_stripe_url'));
  await assertBodyContains(page, config.var('expected_product_price'));
  await assertElementNotPresent(page, 'xpath=(//input[@type=\'radio\'][contains(@name,\'plan\')])[2]');
});
