// AUTO-GENERATED by tests/bin/json-to-playwright.php — edit the converter or JSON source, then regenerate.

import { test } from '@playwright/test';

import { submitStripeCheckoutExpectingDecline } from '../support/checkout-flow-steps';

import { RegressionConfig } from '../support/regression-config';
import { fillCard } from '../support/stripe-steps';

import { SmokeConfig } from '../support/smoke-config';
import { skipUnlessSmokeUrl } from '../support/smoke-skip';

const config = SmokeConfig.fromEnv();
const stripeConfig = RegressionConfig.fromEnv();

test('ST-012 failed Stripe card shows recoverable error', { tag: ["@smoke","@stripe"] }, async ({ page }) => {
  test.setTimeout(300000);
  skipUnlessSmokeUrl(config, 'checkout_stripe_url');

  await page.goto(config.pagePath('checkout_stripe_url'));
  await fillCard(page, stripeConfig, { cardNumber: stripeConfig.var('stripe_card_number_decline') });
  await page.locator('#first_name').fill(config.var('first_name'));
  await page.locator('#last_name').fill(config.var('last_name'));
  await page.locator('#email').fill(config.uniqueEmail('st012'));
  await page.locator('#phone').fill(config.var('phone'));
  await submitStripeCheckoutExpectingDecline(page);
});
