// AUTO-GENERATED by tests/bin/json-to-playwright.php — edit the converter or JSON source, then regenerate.

import { test } from '@playwright/test';

import { assertBodyContains, assertOrderReceived, clickOrderNow } from '../support/checkout-flow-steps';

import { SmokeConfig } from '../support/smoke-config';
import { skipUnlessSmokeUrl } from '../support/smoke-skip';

const config = SmokeConfig.fromEnv();

test('ST-036 100 percent coupon zero total checkout', { tag: ["@smoke"] }, async ({ page }) => {
  test.setTimeout(300000);
  skipUnlessSmokeUrl(config, 'checkout_coupon_url');

  await page.goto(config.pagePath('checkout_coupon_url'));
  await assertBodyContains(page, 'Free access');
  await page.locator('#first_name').fill(config.var('first_name'));
  await page.locator('#last_name').fill(config.var('last_name'));
  await page.locator('#email').fill(config.uniqueEmail('st036'));
  await page.locator('#phone').fill(config.var('phone'));
  await clickOrderNow(page);
  await assertOrderReceived(page);
});
