// AUTO-GENERATED by tests/bin/json-to-playwright.php — edit the converter or JSON source, then regenerate.

import { test } from '@playwright/test';

import { assertManualTaxApplied, fillTaxableAddress } from '../support/checkout-flow-steps';

import { SmokeConfig } from '../support/smoke-config';
import { skipUnlessSmokeUrl } from '../support/smoke-skip';

const config = SmokeConfig.fromEnv();

test('ST-039 manual tax applies for taxable address', { tag: ["@smoke"] }, async ({ page }) => {
  test.setTimeout(300000);
  skipUnlessSmokeUrl(config, 'checkout_tax_url');

  await page.goto(config.pagePath('checkout_tax_url'));
  await fillTaxableAddress(page, {
    line1: config.var('taxable_address_line1'),
    city: config.var('taxable_city'),
    postalCode: config.var('taxable_postal_code'),
  });
  await assertManualTaxApplied(page);
});
