// AUTO-GENERATED by tests/bin/json-to-playwright.php — edit the converter or JSON source, then regenerate.

import { test } from '@playwright/test';

import { SmokeConfig } from '../support/smoke-config';
import { skipUnlessSmokeUrl } from '../support/smoke-skip';

const config = SmokeConfig.fromEnv();

test('ST-054 first upsell accepted', { tag: ["@smoke"] }, async ({ page }) => {
  test.setTimeout(300000);
  skipUnlessSmokeUrl(config, 'checkout_upsell_url');

  await page.goto(config.pagePath('checkout_upsell_url'));
  await page.locator('xpath=//a[contains(.,\'Yes\') or contains(.,\'Add\') or contains(.,\'Accept\')] | //button[contains(.,\'Yes\') or contains(.,\'Add\') or contains(.,\'Accept\')]').click();
});
