// AUTO-GENERATED by tests/bin/json-to-playwright.php — edit the converter or JSON source, then regenerate.

import { expect, test } from '@playwright/test';

import { assertBodyContains } from '../support/checkout-flow-steps';

import { SmokeConfig } from '../support/smoke-config';
import { skipUnlessSmokeUrl } from '../support/smoke-skip';

const config = SmokeConfig.fromEnv();

test('ST-050 order bump accepted', { tag: ["@smoke"] }, async ({ page }) => {
  test.setTimeout(300000);
  skipUnlessSmokeUrl(config, 'checkout_bump_url');

  await page.goto(config.pagePath('checkout_bump_url'));
  await assertBodyContains(page, 'Add this bonus');

  const orderBump = page.locator('#ppcart-orderbump-0 input.ppcart_orderbump');
  await orderBump.waitFor({ state: 'visible', timeout: 30_000 });
  await page.locator('#ppcart-orderbump-0 label').click();
  await expect(orderBump).toBeChecked();
});
