// AUTO-GENERATED by tests/bin/json-to-playwright.php — edit the converter or JSON source, then regenerate.

import { test } from '@playwright/test';

import { assertBodyContains } from '../support/checkout-flow-steps';

import { SmokeConfig } from '../support/smoke-config';
import { skipUnlessSmokeUrl } from '../support/smoke-skip';

const config = SmokeConfig.fromEnv();

test('ST-061 monthly subscription initial purchase', { tag: ["@smoke","@subscription"] }, async ({ page }) => {
  test.setTimeout(300000);
  skipUnlessSmokeUrl(config, 'checkout_subscription_url');

  await page.goto(config.pagePath('checkout_subscription_url'));
  await assertBodyContains(page, 'month');
});
