// AUTO-GENERATED by tests/bin/json-to-playwright.php — edit the converter or JSON source, then regenerate.

import { test } from '@playwright/test';

import { SmokeConfig } from '../support/smoke-config';
import { skipUnlessSmokeUrl } from '../support/smoke-skip';

const config = SmokeConfig.fromEnv();

test('ST-087 backend status after failed payment', { tag: ["@smoke","@stripe"] }, async ({ page }) => {
  test.setTimeout(300000);
  skipUnlessSmokeUrl(config, 'checkout_stripe_url');

  await page.goto(config.pagePath('checkout_stripe_url'));
});
