// AUTO-GENERATED by tests/bin/json-to-playwright.php — edit the converter or JSON source, then regenerate.

import { test } from '@playwright/test';

import { SmokeConfig } from '../support/smoke-config';
import { skipUnlessSmokeUrl } from '../support/smoke-skip';

const config = SmokeConfig.fromEnv();

test('ST-080 admin order list records successful purchase', { tag: ["@smoke","@admin"] }, async ({ page }) => {
  test.setTimeout(300000);
  skipUnlessSmokeUrl(config, 'smoke_admin_path');

  await page.goto(config.pagePath('smoke_admin_path'));
});
