// AUTO-GENERATED by tests/bin/json-to-playwright.php — edit the converter or JSON source, then regenerate.

import { test } from '@playwright/test';

import { SmokeConfig } from '../support/smoke-config';
import { skipUnlessSmokeUrl } from '../support/smoke-skip';

const config = SmokeConfig.fromEnv();

test('ST-085 abandoned checkout is not paid', { tag: ["@smoke","@stripe"] }, async ({ page }) => {
  test.setTimeout(300000);
  skipUnlessSmokeUrl(config, 'checkout_stripe_url');

  await page.goto(config.pagePath('checkout_stripe_url'));
  await page.locator('#email').fill(config.var('test_email'));
  await page.waitForTimeout(10000);
});
