<?php

if (! defined('ABSPATH')) {
    exit;
}

$tab_meta = [
    'general'         => [
        'icon'        => 'shop',
        'group'       => 'shop',
        'description' => __('Currency and pricing defaults for your store.', 'publishpress-cart'),
    ],
    'pages'           => [
        'icon'        => 'pages',
        'group'       => 'shop',
        'description' => __('Choose the customer account page and policy links.', 'publishpress-cart'),
    ],
    'branding'        => [
        'icon'        => 'brand',
        'group'       => 'shop',
        'description' => __('Set the company details and logo used across customer documents.', 'publishpress-cart'),
    ],
    'payment_methods' => [
        'icon'        => 'card',
        'group'       => 'shop',
        'description' => __('Choose which gateways accept payments and configure their keys.', 'publishpress-cart'),
    ],
    'tax'             => [
        'icon'        => 'tax',
        'group'       => 'shop',
        'description' => __('Configure tax rules and tax rates that apply at checkout.', 'publishpress-cart'),
    ],
    'invoice'         => [
        'icon'        => 'invoice',
        'group'       => 'shop',
        'description' => __('Customize how invoices look and what details they include.', 'publishpress-cart'),
    ],
    'downloads'       => [
        'icon'        => 'download',
        'group'       => 'shop',
        'description' => __('Configure secure file download access and URL behavior.', 'publishpress-cart'),
    ],
    'emails'          => [
        'icon'        => 'mail',
        'group'       => 'comms',
        'description' => __('Tune sender details, test messages and customer notifications.', 'publishpress-cart'),
    ],
    'integrations'    => [
        'icon'        => 'plug',
        'group'       => 'comms',
        'description' => __('Connect your store with marketing, analytics and automation tools.', 'publishpress-cart'),
    ],
    'reports'         => [
        'icon'        => 'report',
        'group'       => 'comms',
        'description' => __('Configure sales report recipients and email schedules.', 'publishpress-cart'),
    ],
    'debug'           => [
        'icon'        => 'debug',
        'group'       => 'advanced',
        'description' => __('Enable diagnostic logging and access debug log tools.', 'publishpress-cart'),
    ],
    'maintenance'     => [
        'icon'        => 'sliders',
        'group'       => 'advanced',
        'description' => __('Operational tools including security encryption and credential migration.', 'publishpress-cart'),
    ],
    'advanced'        => [
        'icon'        => 'sliders',
        'group'       => 'advanced',
        'description' => __('Configure store options that do not belong in the main setup tabs.', 'publishpress-cart'),
    ],
    'white_label'     => [
        'icon'        => 'brand',
        'group'       => 'advanced',
        'description' => __('Configure plugin branding, menu labels and white-label documentation links.', 'publishpress-cart'),
    ],
];

// These SVGs are literal plugin-owned strings; keep this array unfiltered.
$icon_svgs = [
    'shop'    => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 9 5 4h14l2 5"/><path d="M3 9v11a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V9"/><path d="M3 9h18"/><path d="M9 13h6"/></svg>',
    'pages'   => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5V5a2 2 0 0 1 2-2h11a3 3 0 0 1 3 3v14H6a2 2 0 0 1-2-2.5Z"/><path d="M8 7h8"/><path d="M8 11h6"/></svg>',
    'brand'   => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3 3 8l9 5 9-5-9-5Z"/><path d="m3 12 9 5 9-5"/><path d="m3 16 9 5 9-5"/></svg>',
    'card'    => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20"/><path d="M6 15h4"/></svg>',
    'tax'     => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 14 21 2"/><circle cx="9.5" cy="6.5" r="2.5"/><circle cx="20.5" cy="17.5" r="2.5"/><path d="M3 21h18"/></svg>',
    'invoice' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M9 13h6"/><path d="M9 17h6"/></svg>',
    'mail'    => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="5" width="20" height="14" rx="2"/><path d="m2 7 10 6 10-6"/></svg>',
    'report'  => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19V5a2 2 0 0 1 2-2h9l5 5v11a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2Z"/><path d="M14 3v6h6"/><path d="M8 17v-4"/><path d="M12 17v-7"/><path d="M16 17v-2"/></svg>',
    'plug'    => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 7V2"/><path d="M15 7V2"/><path d="M5 11h14v3a7 7 0 0 1-14 0v-3z"/><path d="M12 21v-4"/></svg>',
    'download' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/></svg>',
    'debug'   => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M8 2v4"/><path d="M16 2v4"/><rect x="5" y="6" width="14" height="14" rx="2"/><path d="M9 11h.01"/><path d="M15 11h.01"/><path d="M9 16h6"/></svg>',
    'sliders' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 21v-7"/><path d="M4 10V3"/><path d="M12 21v-9"/><path d="M12 8V3"/><path d="M20 21v-5"/><path d="M20 12V3"/><path d="M2 14h4"/><path d="M10 8h4"/><path d="M18 16h4"/></svg>',
    'layers'  => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2 2 7l10 5 10-5-10-5Z"/><path d="m2 12 10 5 10-5"/><path d="m2 17 10 5 10-5"/></svg>',
    'default' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09a1.65 1.65 0 0 0-1-1.51 1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09a1.65 1.65 0 0 0 1.51-1 1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>',
];

$nav_groups = [
    'shop'     => __('Store', 'publishpress-cart'),
    'comms'    => __('Communication & Tools', 'publishpress-cart'),
    'advanced' => __('Advanced', 'publishpress-cart'),
    'other'    => __('More', 'publishpress-cart'),
];

$integration_meta = [
    'activecampaign' => [
        'title'       => __('ActiveCampaign', 'publishpress-cart'),
        'description' => __('Sync customers and purchases to ActiveCampaign.', 'publishpress-cart'),
        'category'    => 'email-marketing',
        'logo_label'  => 'AC',
        'logo_file'   => 'integration-logos/activecampaign.svg',
        'learn_more'  => 'https://www.activecampaign.com/',
        'configured_options' => [ '_ppcart_activecampaign_url', '_ppcart_activecampaign_secret_key' ],
    ],
    'mailchimp'      => [
        'title'       => __('Mailchimp', 'publishpress-cart'),
        'description' => __('Add customers to Mailchimp audiences and automate emails.', 'publishpress-cart'),
        'category'    => 'email-marketing',
        'logo_label'  => 'M',
        'logo_file'   => 'integration-logos/mailchimp.svg',
        'learn_more'  => 'https://mailchimp.com/',
        'configured_options' => [ '_ppcart_mailchimp_api' ],
    ],
    'convertkit'     => [
        'title'       => __('Kit', 'publishpress-cart'),
        'description' => __('Send customers and purchases to Kit forms and tags.', 'publishpress-cart'),
        'category'    => 'email-marketing',
        'logo_label'  => 'K',
        'logo_file'   => 'integration-logos/kit.svg',
        'learn_more'  => 'https://kit.com/',
        'configured_options' => [ '_ppcart_converkit_api', '_ppcart_converkit_secret_key' ],
    ],
    'membervault'    => [
        'title'       => __('MemberVault', 'publishpress-cart'),
        'description' => __('Protect content and manage members with MemberVault.', 'publishpress-cart'),
        'category'    => 'courses',
        'logo_label'  => 'MV',
        'logo_file'   => 'integration-logos/membervault.svg',
        'learn_more'  => 'https://membervault.co/',
        'configured_options' => [ '_ppcart_membervault_name', '_ppcart_member_vault_api_key' ],
    ],
    'sendfox'        => [
        'title'       => __('SendFox', 'publishpress-cart'),
        'description' => __('Grow your audience and send automated emails with SendFox.', 'publishpress-cart'),
        'category'    => 'email-marketing',
        'logo_label'  => 'SF',
        'logo_file'   => 'integration-logos/sendfox.svg',
        'learn_more'  => 'https://sendfox.com/',
        'configured_options' => [ '_ppcart_sendfox_api_key' ],
    ],
    'fbads'          => [
        'title'       => __('Facebook Ad Events', 'publishpress-cart'),
        'description' => __('Send Cart events to an existing Meta Pixel installation. PublishPress Cart does not install or connect the pixel script.', 'publishpress-cart'),
        'category'    => 'ads',
        'logo_label'  => 'f',
        'logo_file'   => 'integration-logos/facebook-ad-events.svg',
        'learn_more'  => 'https://www.facebook.com/business/tools/meta-pixel',
        'enable_options' => [ '_ppcart_fb_add_payment_info', '_ppcart_fb_purchase', '_ppcart_fb_lead' ],
    ],
    'ga'             => [
        'title'       => __('Google Analytics', 'publishpress-cart'),
        'description' => __('Send Cart events to an existing Google Analytics or Google Tag Manager installation. PublishPress Cart does not install or connect the analytics script.', 'publishpress-cart'),
        'category'    => 'analytics',
        'logo_label'  => 'GA',
        'logo_file'   => 'integration-logos/google-analytics.svg',
        'learn_more'  => 'https://analytics.google.com/',
        'enable_options' => [ '_ppcart_ga_purchase', '_ppcart_ga_lead' ],
    ],
    'googlerecaptcha' => [
        'title'       => __('Google reCAPTCHA', 'publishpress-cart'),
        'description' => __('Protect checkout forms from spam and bot submissions.', 'publishpress-cart'),
        'category'    => 'security',
        'logo_label'  => 'G',
        'logo_file'   => 'integration-logos/recaptcha.svg',
        'learn_more'  => 'https://www.google.com/recaptcha/about/',
    ],
    'googlerecaptcha-v2' => [
        'title'       => __('Google reCAPTCHA v2', 'publishpress-cart'),
        'description' => __('Configure checkbox or invisible reCAPTCHA v2 protection.', 'publishpress-cart'),
        'category'    => 'security',
        'logo_label'  => 'G',
        'logo_file'   => 'integration-logos/recaptcha.svg',
        'learn_more'  => 'https://www.google.com/recaptcha/about/',
        'configured_options' => [ '_ppcart_googlerecaptchav2_site_key', '_ppcart_googlerecaptchav2_site_secret' ],
    ],
    'googlerecaptcha-v3' => [
        'title'       => __('Google reCAPTCHA v3', 'publishpress-cart'),
        'description' => __('Configure score-based reCAPTCHA v3 protection.', 'publishpress-cart'),
        'category'    => 'security',
        'logo_label'  => 'G',
        'logo_file'   => 'integration-logos/recaptcha.svg',
        'learn_more'  => 'https://www.google.com/recaptcha/about/',
        'configured_options' => [ '_ppcart_googlerecaptchav3_site_key', '_ppcart_googlerecaptchav3_site_secret' ],
    ],
    'drip'           => [
        'title'       => __('Drip', 'publishpress-cart'),
        'description' => __('Sync customers, tags and ecommerce activity to Drip.', 'publishpress-cart'),
        'category'    => 'email-marketing',
        'logo_label'  => 'D',
        'logo_file'   => 'integration-logos/drip.svg',
        'learn_more'  => 'https://www.drip.com/',
        'configured_options' => [ '_ppcart_drip_id', '_ppcart_drip_api_key' ],
    ],
    'mailerlite'     => [
        'title'       => __('MailerLite', 'publishpress-cart'),
        'description' => __('Add customers to MailerLite subscribers and groups.', 'publishpress-cart'),
        'category'    => 'email-marketing',
        'logo_label'  => 'ML',
        'logo_file'   => 'integration-logos/mailerlite.svg',
        'learn_more'  => 'https://www.mailerlite.com/',
        'configured_options' => [ '_ppcart_mailerlite_api_key' ],
    ],
    'mailpoet'       => [
        'title'       => __('MailPoet', 'publishpress-cart'),
        'description' => __('Add customers to MailPoet lists.', 'publishpress-cart'),
        'category'    => 'email-marketing',
        'logo_label'  => 'MP',
        'logo_file'   => 'integration-logos/mailpoet.svg',
        'learn_more'  => 'https://www.mailpoet.com/',
    ],
    'encharge'       => [
        'title'       => __('Encharge', 'publishpress-cart'),
        'description' => __('Track order events and sync customers to Encharge.', 'publishpress-cart'),
        'category'    => 'email-marketing',
        'logo_label'  => 'E',
        'logo_file'   => 'integration-logos/encharge.svg',
        'learn_more'  => 'https://encharge.io/',
        'enable_options' => [ '_ppcart_encharge_track_events' ],
        'configured_options' => [ '_ppcart_encharge_write_key' ],
    ],
    'fluentcrm'      => [
        'title'       => __('FluentCRM', 'publishpress-cart'),
        'description' => __('Add customers to FluentCRM lists and tags.', 'publishpress-cart'),
        'category'    => 'email-marketing',
        'logo_label'  => 'FC',
        'logo_file'   => 'integration-logos/fluentcrm.svg',
        'learn_more'  => 'https://fluentcrm.com/',
    ],
    'academylms'     => [
        'title'       => __('Academy LMS', 'publishpress-cart'),
        'description' => __('Enroll or remove students from Academy LMS courses.', 'publishpress-cart'),
        'category'    => 'courses',
        'logo_label'  => 'AL',
        'logo_file'   => 'integration-logos/academylms.svg',
        'learn_more'  => 'https://academylms.net/',
    ],
    'gurucan'        => [
        'title'       => __('Gurucan', 'publishpress-cart'),
        'description' => __('Add or remove customers in Gurucan products.', 'publishpress-cart'),
        'category'    => 'courses',
        'logo_label'  => 'G',
        'logo_file'   => 'integration-logos/gurucan.svg',
        'learn_more'  => 'https://www.gurucan.com/',
        'configured_options' => [ '_ppcart_gurucan_app_domain', '_ppcart_gurucan_api_key' ],
    ],
    'heartbeat'      => [
        'title'       => __('Heartbeat', 'publishpress-cart'),
        'description' => __('Manage community access in Heartbeat.', 'publishpress-cart'),
        'category'    => 'courses',
        'logo_label'  => 'H',
        'logo_file'   => 'integration-logos/heartbeat.svg',
        'learn_more'  => 'https://www.heartbeat.chat/',
        'configured_options' => [ '_ppcart_heartbeat_api_key' ],
    ],
    'kajabi'         => [
        'title'       => __('Kajabi', 'publishpress-cart'),
        'description' => __('Enable Kajabi purchase automations.', 'publishpress-cart'),
        'category'    => 'courses',
        'logo_label'  => 'K',
        'logo_file'   => 'integration-logos/kajabi.svg',
        'learn_more'  => 'https://kajabi.com/',
        'enable_options' => [ '_ppcart_kajabi_enable' ],
    ],
    'teachable'      => [
        'title'       => __('Teachable', 'publishpress-cart'),
        'description' => __('Enroll customers into Teachable schools and products.', 'publishpress-cart'),
        'category'    => 'courses',
        'logo_label'  => 'T',
        'logo_file'   => 'integration-logos/teachable.svg',
        'learn_more'  => 'https://teachable.com/',
        'configured_options' => [ '_ppcart_teachable_email', '_ppcart_teachable_password', '_ppcart_teachable_url' ],
    ],
    'upcoach'        => [
        'title'       => __('Upcoach', 'publishpress-cart'),
        'description' => __('Grant customers access to Upcoach programs.', 'publishpress-cart'),
        'category'    => 'courses',
        'logo_label'  => 'UP',
        'logo_file'   => 'integration-logos/upcoach.svg',
        'learn_more'  => 'https://upcoach.com/',
        'configured_options' => [ '_ppcart_upcoach_api_token' ],
    ],
    'tutor'          => [
        'title'       => __('Tutor LMS', 'publishpress-cart'),
        'description' => __('Enroll or remove students from Tutor LMS courses.', 'publishpress-cart'),
        'category'    => 'courses',
        'logo_label'  => 'TL',
        'logo_file'   => 'integration-logos/tutor.svg',
        'learn_more'  => 'https://www.tutorlms.com/',
    ],
    'learndash'      => [
        'title'       => __('LearnDash', 'publishpress-cart'),
        'description' => __('Grant or revoke LearnDash course access.', 'publishpress-cart'),
        'category'    => 'courses',
        'logo_label'  => 'LD',
        'logo_file'   => 'integration-logos/learndash.svg',
        'learn_more'  => 'https://www.learndash.com/',
    ],
    'wpcourseware'   => [
        'title'       => __('WP Courseware', 'publishpress-cart'),
        'description' => __('Manage WP Courseware enrollments after purchase.', 'publishpress-cart'),
        'category'    => 'courses',
        'logo_label'  => 'WPC',
        'logo_file'   => 'integration-logos/wpcourseware.svg',
        'learn_more'  => 'https://flyplugins.com/wp-courseware/',
    ],
    'mslms'          => [
        'title'       => __('MasterStudy LMS', 'publishpress-cart'),
        'description' => __('Enroll customers into MasterStudy LMS courses.', 'publishpress-cart'),
        'category'    => 'courses',
        'logo_label'  => 'MS',
        'logo_file'   => 'integration-logos/masterstudy.svg',
        'learn_more'  => 'https://stylemixthemes.com/wordpress-lms-plugin/',
    ],
    'groups'         => [
        'title'       => __('Groups', 'publishpress-cart'),
        'description' => __('Add or remove customers from WordPress Groups.', 'publishpress-cart'),
        'category'    => 'membership',
        'logo_label'  => 'G',
        'logo_file'   => 'integration-logos/groups.svg',
        'learn_more'  => 'https://wordpress.org/plugins/groups/',
    ],
    'memberpress'    => [
        'title'       => __('MemberPress', 'publishpress-cart'),
        'description' => __('Grant customers MemberPress membership access.', 'publishpress-cart'),
        'category'    => 'membership',
        'logo_label'  => 'MP',
        'logo_file'   => 'integration-logos/memberpress.svg',
        'learn_more'  => 'https://memberpress.com/',
    ],
    'armember'       => [
        'title'       => __('ARMember', 'publishpress-cart'),
        'description' => __('Grant customers ARMember plan access.', 'publishpress-cart'),
        'category'    => 'membership',
        'logo_label'  => 'AR',
        'logo_file'   => 'integration-logos/armember.svg',
        'learn_more'  => 'https://www.armemberplugin.com/',
    ],
    'wishlist'       => [
        'title'       => __('WishList Member', 'publishpress-cart'),
        'description' => __('Grant customers WishList Member level access.', 'publishpress-cart'),
        'category'    => 'membership',
        'logo_label'  => 'WL',
        'logo_file'   => 'integration-logos/wishlist.svg',
        'learn_more'  => 'https://wishlistmember.com/',
    ],
    'rcp'            => [
        'title'       => __('Restrict Content Pro', 'publishpress-cart'),
        'description' => __('Grant customers Restrict Content Pro access.', 'publishpress-cart'),
        'category'    => 'membership',
        'logo_label'  => 'RCP',
        'logo_file'   => 'integration-logos/rcp.svg',
        'learn_more'  => 'https://restrictcontentpro.com/',
    ],
    'um'             => [
        'title'       => __('Ultimate Member', 'publishpress-cart'),
        'description' => __('Send Ultimate Member welcome emails for new customers.', 'publishpress-cart'),
        'category'    => 'membership',
        'logo_label'  => 'UM',
        'logo_file'   => 'integration-logos/ultimate-member.svg',
        'learn_more'  => 'https://ultimatemember.com/',
        'enable_options' => [ '_ppcart_send_um_welcome_email' ],
    ],
    'elementor'      => [
        'title'       => __('Elementor', 'publishpress-cart'),
        'description' => __('Choose Elementor templates for checkout components.', 'publishpress-cart'),
        'category'    => 'builders',
        'logo_label'  => 'E',
        'logo_file'   => 'integration-logos/elementor.svg',
        'learn_more'  => 'https://elementor.com/',
    ],
    'divi'           => [
        'title'       => __('Divi', 'publishpress-cart'),
        'description' => __('Use PublishPress Cart order forms inside Divi layouts.', 'publishpress-cart'),
        'category'    => 'builders',
        'logo_label'  => 'D',
        'logo_file'   => 'integration-logos/divi.svg',
        'learn_more'  => 'https://www.elegantthemes.com/gallery/divi/',
    ],
    'oxygen'         => [
        'title'       => __('Oxygen Builder', 'publishpress-cart'),
        'description' => __('Use PublishPress Cart conditions in Oxygen Builder.', 'publishpress-cart'),
        'category'    => 'builders',
        'logo_label'  => 'O',
        'logo_file'   => 'integration-logos/oxygen.svg',
        'learn_more'  => 'https://oxygenbuilder.com/',
    ],
    'gutenberg'      => [
        'title'       => __('Gutenberg', 'publishpress-cart'),
        'description' => __('Use PublishPress Cart blocks in the WordPress block editor.', 'publishpress-cart'),
        'category'    => 'builders',
        'logo_label'  => 'G',
        'logo_file'   => 'integration-logos/gutenberg.svg',
        'learn_more'  => 'https://wordpress.org/gutenberg/',
    ],
    'woocommerce'    => [
        'title'       => __('WooCommerce', 'publishpress-cart'),
        'description' => __('Connect PublishPress Cart products with WooCommerce flows.', 'publishpress-cart'),
        'category'    => 'automation',
        'logo_label'  => 'W',
        'logo_file'   => 'integration-logos/woocommerce.svg',
        'learn_more'  => 'https://woocommerce.com/',
    ],
    'WPDomainChecker' => [
        'title'       => __('WP Domain Checker', 'publishpress-cart'),
        'description' => __('Sell domains through WP Domain Checker checkout flows.', 'publishpress-cart'),
        'category'    => 'automation',
        'logo_label'  => 'WDC',
        'logo_file'   => 'integration-logos/wp-domain-checker.svg',
        'learn_more'  => 'https://wpdomainchecker.com/',
    ],
    'ppcart_wpdomainchecker' => [
        'title'       => __('WP Domain Checker', 'publishpress-cart'),
        'description' => __('Sell domains through WP Domain Checker checkout flows.', 'publishpress-cart'),
        'category'    => 'automation',
        'logo_label'  => 'WDC',
        'logo_file'   => 'integration-logos/wp-domain-checker.svg',
        'learn_more'  => 'https://wpdomainchecker.com/',
    ],
    'ppcart_subscription' => [
        'title'       => __('Cancel Subscription', 'publishpress-cart'),
        'description' => __('Cancel an existing subscription as an order automation.', 'publishpress-cart'),
        'category'    => 'automation',
        'logo_label'  => 'CS',
    ],
    'ppcart_refund_order' => [
        'title'       => __('Refund Order', 'publishpress-cart'),
        'description' => __('Refund an existing order as an order automation.', 'publishpress-cart'),
        'category'    => 'automation',
        'logo_label'  => 'RO',
    ],
    'webhook'        => [
        'title'       => __('Webhook', 'publishpress-cart'),
        'description' => __('Send order data to an external webhook URL.', 'publishpress-cart'),
        'category'    => 'automation',
        'logo_label'  => '{}',
    ],
];

$integration_categories = [
    'all'             => __('All', 'publishpress-cart'),
    'email-marketing' => __('Email Marketing', 'publishpress-cart'),
    'analytics'       => __('Analytics', 'publishpress-cart'),
    'ads'             => __('Ads', 'publishpress-cart'),
    'automation'      => __('Automation', 'publishpress-cart'),
    'courses'         => __('Courses', 'publishpress-cart'),
    'membership'      => __('Membership', 'publishpress-cart'),
    'security'        => __('Security', 'publishpress-cart'),
    'builders'        => __('Builders', 'publishpress-cart'),
];

$payment_method_meta = [
    'cashondelivery' => [
        'title'        => __('Cash on Delivery', 'publishpress-cart'),
        'panel_title'  => __('Manage Cash on Delivery', 'publishpress-cart'),
        'description'  => __('Allow customers to pay with cash when their order is delivered.', 'publishpress-cart'),
        'logo_label'   => 'COD',
        'manage_label' => __('Manage', 'publishpress-cart'),
    ],
    'stripe'         => [
        'title'        => __('Stripe', 'publishpress-cart'),
        'panel_title'  => __('Manage Stripe', 'publishpress-cart'),
        'description'  => __('Accept credit cards and other payments securely via Stripe.', 'publishpress-cart'),
        'logo_label'   => 'S',
        'logo_file'    => 'payment-logos/stripe.svg',
        'manage_label' => __('Manage Stripe', 'publishpress-cart'),
    ],
    'paypal'         => [
        'title'        => __('PayPal', 'publishpress-cart'),
        'panel_title'  => __('Manage PayPal', 'publishpress-cart'),
        'description'  => __('Accept payments securely via PayPal.', 'publishpress-cart'),
        'logo_label'   => 'P',
        'logo_file'    => 'payment-logos/paypal.svg',
        'manage_label' => __('Manage PayPal', 'publishpress-cart'),
    ],
];

$email_template_meta = [
    'emailtemplate_pending'      => [
        'description' => __('Sent after an order is received (pending payment). Useful for COD orders.', 'publishpress-cart'),
        'recipient'   => __('Customer', 'publishpress-cart'),
    ],
    'emailtemplate_purchase'     => [
        'description' => __('Sent to customers after purchase (paid).', 'publishpress-cart'),
        'recipient'   => __('Customer', 'publishpress-cart'),
    ],
    'emailtemplate_completed'    => [
        'description' => __('Sent when an order is marked complete.', 'publishpress-cart'),
        'recipient'   => __('Customer', 'publishpress-cart'),
    ],
    'emailtemplate_registration' => [
        'description' => __('Sent when a new user account is created.', 'publishpress-cart'),
        'recipient'   => __('Customer', 'publishpress-cart'),
    ],
    'emailtemplate_refunded'     => [
        'description' => __('Sent when an order is refunded.', 'publishpress-cart'),
        'recipient'   => __('Customer', 'publishpress-cart'),
    ],
    'emailtemplate_trial_ending' => [
        'description' => __('Sent before a subscription trial ends.', 'publishpress-cart'),
        'recipient'   => __('Customer', 'publishpress-cart'),
    ],
    'emailtemplate_reminder'     => [
        'description' => __('Sent before an upcoming subscription renewal.', 'publishpress-cart'),
        'recipient'   => __('Customer', 'publishpress-cart'),
    ],
    'emailtemplate_renewal'      => [
        'description' => __('Sent after a subscription renews.', 'publishpress-cart'),
        'recipient'   => __('Customer', 'publishpress-cart'),
    ],
    'emailtemplate_failed'       => [
        'description' => __('Sent when a subscription renewal payment fails.', 'publishpress-cart'),
        'recipient'   => __('Customer', 'publishpress-cart'),
    ],
    'emailtemplate_canceled'     => [
        'description' => __('Sent when a subscription is canceled.', 'publishpress-cart'),
        'recipient'   => __('Customer', 'publishpress-cart'),
    ],
    'emailtemplate_paused'       => [
        'description' => __('Sent when a subscription is paused.', 'publishpress-cart'),
        'recipient'   => __('Customer', 'publishpress-cart'),
    ],
];

if (function_exists('ppcart_email_templates')) {
    foreach (ppcart_email_templates() as $template_type => $template) {
        if (empty($template['section'])) {
            continue;
        }

        $email_template_meta[ $template['section'] ] = [
            'description' => $template['description'] ?? __('Configure this automated email notification.', 'publishpress-cart'),
            'recipient'   => $template['recipient'] ?? __('Customer', 'publishpress-cart'),
            'template'    => $template_type,
        ];
    }
}
