<?php

if (! defined('ABSPATH')) {
    exit;
}


$current_post_id = null;
if (! $save) {
    // phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Read-only use for loading current order/subscription field context.
    $current_post_id = isset($_GET['post']) ? absint(wp_unslash($_GET['post'])) : null;
}
$stripe_read_only = (! $save && $current_post_id && function_exists('ppcart_is_stripe_backed_post') && ppcart_is_stripe_backed_post($current_post_id));

$usersArr = ['' => __('Guest', 'publishpress-cart')];

if (!$save) {
    $user_id = ppcart_get_post_meta($current_post_id, 'user_account', true);
    if (!empty($user_id)) {
        $author_obj = get_user_by('id', $user_id);
        $usersArr[$author_obj->ID] = esc_html($author_obj->display_name);
    }
}

$this->general = [
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_firstname',
        'label'     => __('First Name ', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_lastname',
        'label'     => __('Last Name', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_email',
        'label'     => __('Email', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_phone',
        'label'     => __('Phone', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_company',
        'label'     => __('Company', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_vat_number',
        'label'     => __('VAT Number', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_address1',
        'label'     => __('Address ', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_address2',
        'label'     => __('Address2 ', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_city',
        'label'     => __('City ', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_state',
        'label'     => __('State ', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_zip',
        'label'     => __('Zip ', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'         => 'ppcart-selectize',
        'description'   => '',
        'id'            => '_ppcart_country',
        'label'         => __('Country', 'publishpress-cart'),
        'placeholder'   => '',
        'type'          => 'select',
        'value'         => '',
        'selections'    => ($save) ? '' : array_merge(['' => '--Select--'], is_array(ppcart_countries_list()) ? ppcart_countries_list() : []),
        'class_size' => '',
    ],
    [
        'class'         => 'ppcart-user-search-custom ppcart-selectize',
        'description'   => '',
        'id'            => '_ppcart_user_account',
        'label'         => __('Customer', 'publishpress-cart'),
        'placeholder'   => '',
        'type'          => 'select',
        'value'         => '',
        'selections'    => ($save) ? '' : $usersArr,
        'class_size' => '',
    ],
    [
        'class'         => '',
        'description'   => '',
        'id'            => '_ppcart_status',
        'label'         => __('Order Status', 'publishpress-cart'),
        'placeholder'   => '',
        'type'          => 'select',
        'value'         => '',
        'selections'    => [
            ''                  => __('-- Select --', 'publishpress-cart'),
            'pending'           => __('Pending', 'publishpress-cart'),
            'paid'              => __('Paid', 'publishpress-cart'),
            'completed'         => __('Completed', 'publishpress-cart'),
            'failed'            => __('Failed', 'publishpress-cart'),
            'refunded'          => __('Refunded', 'publishpress-cart'),
            'uncollectible'     => __('Uncollectible', 'publishpress-cart'),
        ],
        'disabled'      => $stripe_read_only,
        'lock_icon'     => $stripe_read_only,
        'note'          => '',
        'class_size' => '',
    ],
    [
        'class'         => '',
        'description'   => '',
        'id'            => '_ppcart_product_id',
        'label'         => __('Product', 'publishpress-cart'),
        'placeholder'   => '',
        'type'          => 'select',
        'value'         => '',
        'selections'    => ($save) ? '' : $this->get_products(),
        'class_size' => '',
    ],
    [
        'class'         => '',
        'description'   => '',
        'id'            => '_ppcart_item_name',
        'label'         => __('Payment Plan', 'publishpress-cart'),
        'placeholder'   => '',
        'type'          => 'select',
        'value'         => '',
        'selections'    => ($save) ? '' : $this->get_products_payment(),
        'class_size' => '',
    ],
];

$this->sub_fields = [
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_firstname',
        'label'     => __('First Name ', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_lastname',
        'label'     => __('Last Name', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_email',
        'label'     => __('Email', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_phone',
        'label'     => __('Phone', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_company',
        'label'     => __('Company', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_vat_number',
        'label'     => __('VAT Number', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_address1',
        'label'     => __('Address ', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_address2',
        'label'     => __('Address2 ', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_city',
        'label'     => __('City ', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_state',
        'label'     => __('State ', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'     => 'widefat',
        'description'   => '',
        'id'            => '_ppcart_zip',
        'label'     => __('Zip ', 'publishpress-cart'),
        'placeholder'   => '',
        'type'      => 'text',
        'value'     => '',
    ],
    [
        'class'         => 'ppcart-selectize',
        'description'   => '',
        'id'            => '_ppcart_country',
        'label'         => __('Country', 'publishpress-cart'),
        'placeholder'   => '',
        'type'          => 'select',
        'value'         => '',
        'selections'    => ($save) ? '' : ppcart_countries_list(),
        'class_size' => '',
    ],
    [
        'class'         => 'ppcart-user-search-custom ppcart-selectize',
        'description'   => '',
        'id'            => '_ppcart_user_account',
        'label'         => __('Customer', 'publishpress-cart'),
        'placeholder'   => '',
        'type'          => 'select',
        'value'         => '',
        'selections'    => ($save) ? '' : $usersArr,
        'class_size' => '',
    ],
];
