name: Deploy plugin to WordPress.org

on:
  release:
    types: [ released ]

jobs:
  code-standards:
    name: Check code standards
    uses: ./.github/workflows/code-standards.yml
    secrets: inherit

  code-complexity:
    name: Analyze code complexity
    uses: ./.github/workflows/code-complexity.yml
    secrets: inherit

  unit-tests:
    name: Run unit tests
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit

  integration-tests:
    name: Run integration tests
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit

  deploy-wp-org:
    permissions:
      contents: write
    uses: publishpress/github-workflows/.github/workflows/deploy-free.yml@v3
    needs: [code-standards, code-complexity, unit-tests, integration-tests]
    secrets: inherit
